version: '3'
services:
  python_app:
    image: moiwa/workflow_tag:${TAG:-latest}
    ports:
      - "${OUTER_PORT:-8000}:8000"
    networks:
      - monitoring
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.ImageName}}|{{.Name}}"

  loki:
    image: grafana/loki:${LOKI_VERSION}
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - ./loki-config.yml:/etc/loki/loki-config.yml
      - loki-data:/tmp/loki/
    networks:
      - monitoring
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.ImageName}}|{{.Name}}"
    deploy:
      resources:
        limits:
          memory: 300M

  #lab7
  grafana:
    image: grafana/grafana:${GRAFANA_VERSION}
    ports:
      - "3000:3000"
    networks:
      - monitoring
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.ImageName}}|{{.Name}}"
    deploy:
      resources:
        limits:
          memory: 300M

  promtail:
    image: grafana/promtail:${PROMTAIL_VERSION}
    ports:
      - "9080:9080"
    volumes:
      - /var/log:/var/log
      - /var/lib/docker/containers/:/var/lib/docker/containers/
      - ./promtail.yml:/etc/promtail/config.yml
    command: -config.file=/etc/promtail/config.yml
    networks:
      - monitoring
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.ImageName}}|{{.Name}}"
    deploy:
      resources:
        limits:
          memory: 300M

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command: --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    networks:
      - monitoring
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.ImageName}}|{{.Name}}"
    deploy:
      resources:
        limits:
          memory: 300M




networks:
  monitoring:

volumes:
  prometheus-data: {}
  grafana-data: {}
  loki-data: {}
  promtail-data: {}