version: '3'
services:
  python_app:
    image: moiwa/workflow_tag:${TAG:-latest}
    volumes:
      - app-data:/usr/src/app_python
    ports:
      - "${OUTER_PORT:-8000}:8000"
    networks:
      - monitoring
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"
        tag: "{{.ImageName}}|{{.Name}}"



networks:
  monitoring:

volumes:
  app-data: {}