apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-node
  labels:
    app: app-python
spec:
  replicas: 3
  selector:
    matchLabels:
      app: app-python
  template:
    metadata:
      labels:
        app: app-python
    spec:
      containers:
      - name: app-python
        image: moiwa/workflow_tag
        ports:
        - containerPort: 8000