apiVersion: v1
kind: Service
metadata:
  name: devops-node
spec:
  selector:
    app: app-python
  type: NodePort
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30000