name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - name: Cache static
        uses: actions/cache@v2.1.6
        env:
          cache-name: cache-static
        with:
          path: ./app_python/static
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
      - name: Cache templates
        uses: actions/cache@v2.1.6
        env:
          cache-name: cache-templates
        with:
          path: ./app_python/static
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}


      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}



      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          cd app_python
          pip install -r requirements.txt



      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          id: cache_dependencies
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
          python -m pip install --upgrade pip
          cd app_python
          pip install -r requirements.txt
      - name: Docker Layer Caching
        uses: satackey/action-docker-layer-caching@v0.0.11
      - uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true
      - name: Build Image
        run: |
          cd app_python
          sudo docker build -t moiwa/workflow_tag .
      - name: Run Tests
        run: |
          cd app_python
          python manage.py test

  test:
    needs: build
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 1
      matrix:
        python-version: [3.7]

    steps:
      - uses: actions/checkout@v2
      - uses: actions/cache@v1
        with:
          path: ~/.cache/pip
          id: cache_dependencies
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - name: Install
        if: steps.cache.outputs.cache-hit != 'true'
        run: |
            python -m pip install --upgrade pip
            cd app_python
            pip install -r requirements.txt

      - name: Run Tests
        run: |
          cd app_python
          python manage.py test


  deploy:
    needs: test
    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
      - name: Deploy Image
        run: |
          sudo docker push moiwa/workflow_tag