name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-18.04
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache python    
      uses: actions/cache@v2.1.6
      with:
        ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        cd app_python
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        cd app_python
        python manage.py test
    - name: Build Image
      run: |
        cd app_python
        sudo docker build -t workflow_tag .
